apiVersion: apps/v1
kind: Deployment 
metadata:
  name: clusterip-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ClusterIPapp
  template:
    metadata:
      labels:
        app: ClusterIPapp
    spec:
      containers:
        - name: clusterip-container
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion:  v1 
kind: Service 
metadata: 
  name: clusterip-service
spec:
  selector: 
    app:  ClusterIPapp
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
  type: ClusterIP

  