apiVersion: apps/v1
kind: Deployment 
metadata:
  name: lb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lbapp
  template:
    metadata:
      labels:
        app: lbapp
    spec:
      containers:
        - name: lb-container
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion:  v1 
kind: Service 
metadata: 
  name: lb-service
spec:
  selector: 
    app: lbapp
  ports:
    - protocol: TCP
      port: 81 #service port
      targetPort: 80
  type: LoadBalancer