apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodeport-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodeportapp
  template:
    metadata:
      labels:
        app: nodeportapp
    spec:
      containers:
        - name: nodeport-container
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion:  v1 
kind: Service 
metadata: 
  name: nodeport-service
spec:
  selector: 
    app:  nodeportPapp
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30200
  type: NodePort