apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec: 
      containers:
        - name: nginx-maincontiner
          image: nginx 
          ports:
            - containerPort: 80